name: sentinel_guard
description: "Premium parental control app with advanced monitoring and protection features"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  shimmer: ^3.0.0
  animate_do: ^3.1.2
  google_fonts: ^6.1.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # App Launching & Web
  android_intent_plus: ^4.0.3
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  external_app_launcher: ^4.0.3
  
  # Screen Time
  usage_stats: ^1.3.0
  
  # Biometric Authentication
  local_auth: ^2.1.8
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
